baseURL = "/"
languageCode = "en-us"
paginate = 6
theme = "portio-hugo"
title = "Portio"

######################## Markup ##################################
[markup.goldmark.renderer]
  unsafe = true

######################## Build Cache Busters #####################
[build]
  [build.cachebusters]
    [build.cachebusters.js]
      dir = ":assetDir/js"
      filename = ":filename"
    [build.cachebusters.css]
      dir = ":assetDir/scss"
      filename = ":filename"
    [build.cachebusters.assets]
      dir = ":assetDir"
      filename = ":filename"

######################## Outputs #################################
[outputs]
  home = ["HTML", "RSS"]

######################## Imaging #################################
[imaging]
  quality = 90
  resampleFilter = "Lanczos"

######################## Services ################################
[services]
  [services.googleAnalytics]
    ID = "YOUR GOOGLE ANALYTICS CODE"
  [services.disqus]
    shortname = ""

######################## Main Menu ###############################
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

######################## Sitemap Menu ############################
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

######################## Site Params #############################
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
# Form backend service — paste your fabform/formspree URL below
fabformURL = "https://fabform.io/f/JpTXRUa"
logo = "images/site-navigation/logo.png"

[params.address]
address = "23 Khan Niketon, Grand Street, NYK."
email = "hello@example.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(448) 833 5272 332"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

######################## CSS Plugins #############################
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/font-awesome/css/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/magnafic-popup/magnific-popup.css"

######################## JS Plugins ##############################
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/waypoint/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/magnafic-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/tweenmax/TweenMax.min.js"
[[params.plugins.js]]
link = "plugins/imagesloaded/imagesloaded.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"

######################## Social Icons ############################
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
